### ISSUE TITLE
Improve UX for distribution exploration in VaR notebook

### ISSUE THREAD

**Issue by willb** [radanalyticsio/workshop-notebook#12]
Thanks to @Jiri-Kremser for the suggestion, which follows:

> It would be nice to have a combobox with all the supported distrubutions that helps w/ the last step in the notebook... to find the better distribution than the normal one (http://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html)

**Comment by jkremser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [drop down menu w/ available distributions for the var notebook](https://trello.com/c/1osD74bv/483-drop-down-menu-w-available-distributions-for-the-var-notebook)
